name: Django CI

on:
  push:
    branches: [ "Affin-updated" ]
  pull_request:
    branches: [ "Affin-updated" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]  # Added Python 3.12

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # Explicitly install distutils for Python 3.12+
        if [[ "${{ matrix.python-version }}" == "3.12" ]]; then
          pip install setuptools==68.0.0  # Use a compatible setuptools version
        fi
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
